### ISSUE TITLE
tiny-menu-run-item broken in melpa

### ISSUE THREAD

**Issue by tslilc** [aaronbieber/tiny-menu.el#3]
The function seems a little confused, and won't work as is.

```
(defun tiny-menu-run-item (item)
  (let ((menu-item item))
    (lambda ()
      (interactive)
      (tiny-menu item))))
```

~~You say it's a macro in the docs IIRC, but it's written with a defun.~~ It _could_ be a macro, but an easy fix is to make the body

```
`(lambda () (interactive) (tiny-menu ,item)))
```

which allows us to write the `define-key` as you had imagined it.

**Comment by aaronbieber** [comment]
You are right, I am sorry about this.

I had written it as a macro originally, but Steve Purcell advised me to rewrite it as a function because macros shouldn't be used where a regular function will do. I implemented it using lexical binding, but did it wrong and didn't know because I was inadvertently loading a different version of the library left behind from MELPA build testing.

Anyway, the reason it wasn't working was because the `-*- lexical-binding: t -*-` line was not entered properly and wasn't being evaluated. I am preparing an update that will be up in a few minutes.

**Comment by aaronbieber** [comment]
Again sorry about that, give this patch a shot and let me know if it doesn't work for you.

**Comment by tslilc** [comment]
Brilliant, thanks for the swift response. Unfortunately I was hard at work wrecking your beautiful code (as you will see) so I haven't yet had a chance to test this. Anyway, thanks again.
